# Generated by Django 3.0.7 on 2020-07-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lisitng',
            new_name='Listing',
        ),
    ]
